remote_theme: just-the-docs/just-the-docs
title: Self-Inheritance Protocol
description: A protocol for securing Bitcoin inheritance across generations
author: Quentin Ehrenmann
url: "https://protocol.thebitcoinbackup.com"
baseurl: ""

# Navigation
aux_links:
  "View on GitHub":
    - "//github.com/TheBitcoinBackup/Self-Inheritance-Protocol"
aux_links_new_tab: true

# Footer content
footer_content: "Created by The Bitcoin Backup · <a href='https://thebitcoinbackup.com'>thebitcoinbackup.com</a>"
